import { Injectable } from '@angular/core';

// Clase de Propieades Globales de la PGC
@Injectable()
export class ListEndPointsService {

  constructor() { }

  // Listado de los End Point que seran usados en la API ********************************
  // Json de los End Points de la API disponibles
  getEndPoint = {
    endPointEstados: {
      listAllEstados: {
        id: 1,
        nameEndpoint: 'ListAllEstados',
        urlEndPoint: '/estados',
        groupEndPoint: 'estadosGroup',
        descEndPoint: 'Busca todos los Estados de la API',
      },
      listAllEstadosActividades: {
        id: 2,
        nameEndpoint: 'ListAllEstadosActividades',
        urlEndPoint: '/estados/findByIdGrupo/',
        groupEndPoint: 'estadosGroup',
        descEndPoint: 'Busca todos los Estados de la API, que sean de Actividades',
      },
      listAllTipoActividades: {
        id: 3,
        nameEndpoint: 'ListAllTipoActividades',
        urlEndPoint: '/tipos/findByIdGrupo/',
        groupEndPoint: 'estadosGroup',
        descEndPoint: 'Busca todos los Estados de la API, que sean de Actividades',
      },
    },
    endPointUsers: {
      findByMail: {
        id: 1,
        nameEndpoint: 'findByMail',
        urlEndPoint: '/usuarios/findByMail/',
        groupEndPoint: 'userGroup',
        descEndPoint: 'Busca el Usuario con el Email, de parametro',
      },
      getSecuencia: {
        id: 2,
        nameEndpoint: 'Get Secuencia',
        urlEndPoint: '/secuencias/findByIdSecuencia/',
        groupEndPoint: 'userGroup',
        descEndPoint: 'Busca la Secuencia con el ID Enviado',
      },
      getSecuenciabyCod: { // NAM | 2019-01-21 | Secuencias de Actividad
        id: 3,
        nameEndpoint: 'Get Secuencia by Cod',
        urlEndPoint: '/secuencias/findByCodSecuencia/',
        groupEndPoint: 'userGroup',
        descEndPoint: 'Busca la Secuencia con el Codigo Enviado',
      },
      updateSecuence: {
        id: 4,
        nameEndpoint: 'Actualizacion de la Secuencia',
        urlEndPoint: '/secuencias/update/',
        groupEndPoint: 'userGroup',
        descEndPoint: 'Actualiza la Secuencia de la Actividad',
      },
    },
    endPointMantActividades: {
      listAllSectorEjecutor: {
        id: 1,
        nameEndpoint: 'ListAllSectoresEjecutores',
        urlEndPoint: '/mant-actividades/sector-ejecutor',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca el listado de los Sectores Ejecutores de la Actividad',
      },
      getSectorEjecutor: {
        id: 2,
        nameEndpoint: 'getSectorEjecutor',
        urlEndPoint: '/mant-actividades/sector-ejecutor/findById/',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca el Sectores Ejecutor de la Actividad',
      },
      listAllEstrategia: {
        id: 3,
        nameEndpoint: 'ListAllSEstrategia',
        urlEndPoint: '/mant-actividades/estrategia',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca el listado de los Sectores Ejecutores de la Actividad',
      },
      getEstrategia: {
        id: 4,
        nameEndpoint: 'getEstrategia',
        urlEndPoint: '/mant-actividades/estrategia/findById/',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca el Sectores Ejecutor de la Actividad',
      },
      listAllPresupuesto: {
        id: 5,
        nameEndpoint: 'listAllPresupuesto',
        urlEndPoint: '/mant-actividades/presupuesto',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca el listado de los Presupuesto de la Actividad',
      },
      getPresupuesto: {
        id: 6,
        nameEndpoint: 'getPresupuesto',
        urlEndPoint: '/mant-actividades/presupuesto/findById/',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca el Presupuesto de la Actividad',
      },
      getTiposIniciativasCSS: { // NAM | 2019-02-07 | Tipos de Iniciativa
        id: 7,
        nameEndpoint: 'getTiposIniciativasCSS',
        urlEndPoint: '/mant-actividades/tipo-iniciativa',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca los Tipos de Iniciativa de CSS',
      },
      getAllMonedasActividad: { // NAM | 2019-05-21 | Monedas de Actividad
        id: 8,
        nameEndpoint: 'getAllMonedasActividad',
        urlEndPoint: '/mant-actividades/moneda-actividad',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca todas las Monedas para el financiamiento',
      },
      getMonedaActividad: {
        id: 9,
        nameEndpoint: 'getMonedaActividad',
        urlEndPoint: '/mant-actividades/moneda-actividad/findById/',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca la Moneda para el financiamiento',
      },
      getAllTipoFinanciamiento: { // NAM | 2019-05-27 | Tipo de Financiamiento
        id: 10,
        nameEndpoint: 'getAllTipoFinanciamiento',
        urlEndPoint: '/mant-actividades/tipo-financiamiento',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca todas los tipos financiamiento',
      },
      getTipoFinanciamiento: {
        id: 11,
        nameEndpoint: 'getTipoFinanciamiento',
        urlEndPoint: '/mant-actividades/tipo-financiamiento/findById/',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca el tipo financiamiento',
      },
      getAllModalidadAyuda: {
        id: 12,
        nameEndpoint: 'getAllModalidadAyuda',
        urlEndPoint: '/mant-actividades/modalidad-ayuda',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca todas las Modalidades de Ayudas',
      },
      getModalidadAyuda: {
        id: 13,
        nameEndpoint: 'getModalidadAyuda',
        urlEndPoint: '/mant-actividades/modalidad-ayuda/findById/',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca la Modalidad de Ayuda',
      },
      getAllTipoTransaccion: {
        id: 14,
        nameEndpoint: 'getAllTipoTransaccion',
        urlEndPoint: '/mant-actividades/tipo-transaccion',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca todas los Tipos de Transaccion',
      },
      getTipoTransaccion: {
        id: 15,
        nameEndpoint: 'getTipoTransaccion',
        urlEndPoint: '/mant-actividades/tipo-transaccion/findById/',
        groupEndPoint: 'matActGroup',
        descEndPoint: 'Busca el Tipo de Transaccion',
      },
    },
    endPointEspaciosTrabajo: {
      listAllEspaciosTrabajo: {
        id: 1,
        nameEndpoint: 'ListAllEspaciosTrabajo',
        urlEndPoint: '/espacios-trabajo',
        groupEndPoint: 'espacioTrabajoGroup',
        descEndPoint: 'Busca todos los Espacios de Trabajo de la API',
      },
      findByIdEspacioTrabajo: {
        id: 2,
        nameEndpoint: 'findByIdEspaciotrabajo',
        urlEndPoint: '/espacios-trabajo/findByIdEspaciotrabajo/',
        groupEndPoint: 'espacioTrabajoGroup',
        descEndPoint: 'Busca los espacios de trabajo con el IdEspacioTrabajo, de parametro',
      },
      newEspacioTrabajo: {
        id: 3,
        nameEndpoint: 'newEspacioTrabajo',
        urlEndPoint: '/espacios-trabajo/new',
        groupEndPoint: 'espacioTrabajoGroup',
        descEndPoint: 'Ingresa un nuevo Espacio de Trabajo en la BD',
      },
      editEspacioTrabajo: {
        id: 4,
        nameEndpoint: 'editEspacioTrabajo',
        urlEndPoint: '/espacios-trabajo/edit/',
        groupEndPoint: 'espacioTrabajoGroup',
        descEndPoint: 'Actualiza un Espacio de Trabajo en la BD',
      },
      deleteEspacioTrabajo: {
        id: 5,
        nameEndpoint: 'deleteEspacioTrabajo',
        urlEndPoint: '/espacios-trabajo/delete/',
        groupEndPoint: 'espacioTrabajoGroup',
        descEndPoint: 'Elimina un Espacio de Trabajo en la BD',
      },
    },
    endPointEspaciosTrabajoUsuarios: {
      listAllEspaciosTrabajoUsuarios: {
        id: 1,
        nameEndpoint: 'ListAllEspaciosTrabajoUsuarios',
        urlEndPoint: '/espacios-trabajo-usuario',
        groupEndPoint: 'espacioTrabajoUsuarioGroup',
        descEndPoint: 'Busca todos los Espacios de Trabajo de la API que han sido asignados a los Usuarios',
      },
      findByIdEspacioTrabajoUsuarios: {
        id: 2,
        nameEndpoint: 'FindByIdEspacioTrabajoUsuarios',
        urlEndPoint: '/espacios-trabajo-usuario/findByIdEspaciotrabajousuario/',
        groupEndPoint: 'espacioTrabajoUsuarioGroup',
        descEndPoint: 'Busca el Espacio de Trabajo con el ID Espacio de Trab/User, de parametro',
      },
      newEspacioTrabajoUsuarios: {
        id: 3,
        nameEndpoint: 'NewEspacioTrabajoUsuarios',
        urlEndPoint: '/espacios-trabajo-usuario/new',
        groupEndPoint: 'espacioTrabajoUsuarioGroup',
        descEndPoint: 'Ingresa un nuevo Espacio de Trabajo en la BD asignandolo a un Usuario',
      },
      findByIdUsuarioEspacioTrabajo: {
        id: 4,
        nameEndpoint: 'FindByIdUsuarioEspacioTrabajo',
        urlEndPoint: '/espacios-trabajo-usuario/findByIdUsuarioEspacioTrabajo/',
        groupEndPoint: 'espacioTrabajoUsuarioGroup',
        descEndPoint: 'Busca los espacios de trabajo asignados al Usuario con el IdUsuario, de parametro',
      },
    }, // Modulo de Organizaciones
    endPointOrganizaciones: { // DRP NUEVO TIPO DE ORGANIZACION
      listAllTipoOrganizaciones: {
        id: 1,
        nameEndpoint: 'ListAllTipoOrganizaciones',
        urlEndPoint: '/tipos-organizaciones',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca todos los Tipos de Organizaciones de la API',
      },
      findByIdTipoOrganizacion: {
        id: 2,
        nameEndpoint: 'FindByIdTipoOrganizacion',
        urlEndPoint: '/tipos-organizaciones/findByIdTipoOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca el Tipo de Organizacion con el IdTipoOrganizacion, de parametro',
      },
      newTipoOrganizacion: {
        id: 3,
        nameEndpoint: 'NewTipoOrganizacion',
        urlEndPoint: '/tipos-organizaciones/new',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Ingresa un nuevo Espacio de Trabajo en la BD asignandolo a un Usuario',
      },
      listAllOrganizaciones: {
        id: 4,
        nameEndpoint: 'ListAllOrganizaciones',
        urlEndPoint: '/organizaciones',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca todos las Organizaciones de la API',
      },
      findByIdOrganizacion: {
        id: 5,
        nameEndpoint: 'FindByIdOrganizacion',
        urlEndPoint: '/organizaciones/findByIdOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca el Tipo de Organizacion con el IdTipoOrganizacion, de parametro',
      },
      findByIdTipoOrganizacionT: {
        id: 6,
        nameEndpoint: 'FindByIdOrganizacion',
        urlEndPoint: '/organizaciones/findByIdTipoOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca el Tipo de Organizacion con el IdTipoOrganizacion, de parametro',
      },
      findByIdTipoPaisOrganizacion: {
        id: 7,
        nameEndpoint: 'FindByIdOrganizacion',
        urlEndPoint: '/organizaciones/findByIdTipoPaisOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca la Organizacion con el IdTipoOrganizacion, de parametro',
      },
      newOrganizacion: {
        id: 8,
        nameEndpoint: 'NewOrganizacion',
        urlEndPoint: '/organizaciones/new',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Ingresa un nueva Organizacion en la BD asignandolo',
      }, // 2018-10-20 | NAM
      findByIdPaisOrganizacion: {
        id: 9,
        nameEndpoint: 'findByIdPaisOrganizacion',
        urlEndPoint: '/organizaciones/findByIdPaisOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca la Organizacion con el IdPaisOrganizacion, de parametro',
      }, // NAM | 2019-01-09 | Creacion del EndPoint de Buscar Org. por Codido
      findByCodOrganizacion: {
        id: 10,
        nameEndpoint: 'Find By CodOrganizacion',
        urlEndPoint: '/organizaciones/findByCodOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca la Organizacion con el CodOrganizacion, de parametro',
      },
      countByCodOrganizacion: {
        id: 11,
        nameEndpoint: 'Find By CodOrganizacion Count',
        urlEndPoint: '/organizaciones/countByCodOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca la Organizacion con el CodOrganizacion, de parametro',
      },
      updateTipoOrganizacion: {
        id: 12,
        nameEndpoint: 'updateTipoOrganizacion',
        urlEndPoint: '/tipos-organizaciones/update/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Actualizar eñ tipo de organizaciones ',
      },
      deleteTipoOrganizacion: {
        id: 13,
        nameEndpoint: 'deleteTipoOrganizacion',
        urlEndPoint: '/tipos-organizaciones/delete/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'inhabilitar el tipo de organizaciones ',
      },
      listAllCategoriaOrganizaciones: {
        id: 14,
        nameEndpoint: 'listAllCategoriaOrganizaciones',
        urlEndPoint: '/categorias-organizaciones',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Listar todas las Categorias de Organizacion',
      },
      findByIdCatOrganizacion: {
        id: 15,
        nameEndpoint: 'findByIdCatOrganizacion',
        urlEndPoint: '/categorias-organizaciones/findByIdCatOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Buscar Categoria de Organzicion con el Id como Parametro',
      },
      findByIdTipoOrganizacionCat: {
        id: 16,
        nameEndpoint: 'findByIdTipoOrganizacionCat',
        urlEndPoint: '/categorias-organizaciones/findByIdTipoOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Buscar todas las Categorias de Organizacion, con el Tipo como parametro',
      },
      newCatOrganizacionCat: {
        id: 17,
        nameEndpoint: 'newCatOrganizacionCat',
        urlEndPoint: '/categorias-organizaciones/new',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Ingresar la Categoria de Organizacion',
      },
      updateCatOrganizacionCat: {
        id: 18,
        nameEndpoint: 'updateCatOrganizacionCat',
        urlEndPoint: '/categorias-organizaciones/update/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'actualizar las categorias',
      },
      deleteCatOrganizacionCat: {
        id: 19,
        nameEndpoint: 'updateCatOrganizacionCat',
        urlEndPoint: '/categorias-organizaciones/delete/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'inhabilitar las categorias',
      },
      findByIdTipoPaisCategoriaOrganizacion: {
        id: 20,
        nameEndpoint: 'FindByIdTipoPaisCategoriaOrganizacion',
        urlEndPoint: '/organizaciones/findByIdTipoPaisCategoriaOrganizacion/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Busca la Organizacion con el IdTipo, IdPais y IdCategoria de Organizacion , de parametro',
      },
      UpdateOrganizaciones: {
        id: 21,
        nameEndpoint: 'updateOrganizaciones',
        urlEndPoint: '/organizaciones/edit/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Actualizar las orgnizacion',
      },
      deleteOrganizacion: {
        id: 22,
        nameEndpoint: 'deleteOrganizaciones',
        urlEndPoint: '/organizaciones/delete/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'inhabilitar las orgnizaciones',
      },
      caseOrganizacion: {
        id: 23,
        nameEndpoint: 'caseOrganizacion',
        urlEndPoint: '/organizaciones/findByBoolean/',
        groupEndPoint: 'organizacionesGroup',
        descEndPoint: 'Escoger las Organizaciones segun el area indicada',
      },
    }, // Modulo de Mantenimientos Genericos
    endPointMantGenericos: {
      listAllPaises: {
        id: 1,
        nameEndpoint: 'ListAllPaises',
        urlEndPoint: '/ubicacion-geografica/pais',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'Busca todos los Paises de la API',
      },
      findByIdTipoOrganizacion: {
        id: 2,
        nameEndpoint: 'FindByIdTipoOrganizacion',
        urlEndPoint: '/ubicacion-geografica/pais/',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'Busca el Pais con el IdPais, de parametro',
      },
      newTipoOrganizacion: {
        id: 3,
        nameEndpoint: 'NewTipoOrganizacion',
        urlEndPoint: '/espacios-trabajo-usuario/new',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'Ingresa un nuevo Espacio de Trabajo en la BD asignandolo a un Usuario',
      },
      listAllPerfiles: {
        id: 4,
        nameEndpoint: 'List All Perfiles',
        urlEndPoint: '/profiles',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'Listar todos los Perfiles',
      },
      newPerfil: {
        id: 5,
        nameEndpoint: 'nuevo perfil',
        urlEndPoint: '/profiles/new',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'crear nuevo Perfiles',
      },
      getAllTipoPerfil: {
        id: 6,
        nameEndpoint: 'listar tipo perfil',
        urlEndPoint: '/profiles/kind',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'listar los tipo de perfiles',
      },
      perfilUpdate: {
        id: 7,
        nameEndpoint: 'Actualizar los perfiles',
        urlEndPoint: '/profiles/edit/',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'Actualizar los perfiles',
      },
      deletePerfil: {
        id: 8,
        nameEndpoint: 'inhabilitar los perfiles',
        urlEndPoint: '/profiles/delete/',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'inhabilita los perfiles',
      },
      getAllTipoRol: {
        id: 9,
        nameEndpoint: 'listar tipo rol',
        urlEndPoint: '/roles/findByIdGrupo/',
        groupEndPoint: 'mantGenericosGroup',
        descEndPoint: 'listar los tipos de roles',
      },
    }, // Modulo de Mantenimientos Genericos
    endPointIdInternasActividades: {
      listAllidInternas: {
        id: 1,
        nameEndpoint: 'List All Id Internas',
        urlEndPoint: '/mant-actividades/id-interna',
        groupEndPoint: 'idInternaGroup',
        descEndPoint: 'Busca todos los Paises de la API',
      },
      findByCodInterna: {
        id: 2,
        nameEndpoint: 'Find By CodInterna',
        urlEndPoint: '/mant-actividades/id-interna/findByCodInterna/',
        groupEndPoint: 'idInternaGroup',
        descEndPoint: 'Busca la Id Interna con el Codigo enviado',
      },
      countByCodInterna: {
        id: 3,
        nameEndpoint: 'Count By CodInterna',
        urlEndPoint: '/mant-actividades/id-interna/countByCodInterna/',
        groupEndPoint: 'idInternaGroup',
        descEndPoint: 'Busca la Cantidad de Id Internas con el Codigo enviado',
      },
    },
    // Modulo de CRUD Activiades | Datos Generales
    endPointCRUDActividades: {
      newActivityDatosGenerales: {
        id: 1,
        nameEndpoint: 'Nueva Actividad',
        urlEndPoint: '/activities/new-activity',
        params: 'jsonActivity',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresa a la API una nueva Actividad con sus Datos Generales',
      },
      editActivityDatosGenerales: {
        id: 2,
        nameEndpoint: 'Editar Actividad',
        urlEndPoint: '/activities/edit-activity/',
        params: '{idActivity}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Edita en la API, una Actividad con sus Datos Generales',
      },
      deleteActivityDatosGenerales: {
        id: 3,
        nameEndpoint: 'Eliminar Actividad',
        urlEndPoint: '/activities/delete-activity/',
        params: '{idActivity}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Inhabilita en la API, una Actividad con sus Datos Generales',
      }, // NAM | 2019-02-08 | Mapping Planificacion de Actividades
      newActivityPlanificacion: {
        id: 4,
        nameEndpoint: 'Agregar Planificacion a Proyecto',
        urlEndPoint: '/mant-actividades/planificacion/new',
        params: '{jsonActivityPlanificacion}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Agregar la Planificacion al proyecto recien Ingresado',
      },
      editActivityPlanificacion: {
        id: 5,
        nameEndpoint: 'Actualizar Planificacion a Proyecto Editado',
        urlEndPoint: '/mant-actividades/planificacion/edit/',
        params: '{jsonActivityPlanificacion, idActividadPlan}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Actualizar la Planificacion al proyecto a Editar',
      },
      deleteActivityPlanificacion: {
        id: 6,
        nameEndpoint: 'Eliminar Planificacion a Proyecto',
        urlEndPoint: '/mant-actividades/planificacion/edit/',
        params: '{jsonActivityPlanificacion, idActividadPlan}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar la Planificacion al proyecto a Editar',
      }, // NAM | 2019-02-08 | Mapping Planificacion de Actividades
      newActivityIdInterna: {
        id: 7,
        nameEndpoint: 'Agregar Id Interna a Proyecto',
        urlEndPoint: '/mant-actividades/id-interna/new',
        params: '{jsonActivityIdInterna}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Agregar la Id Interna al proyecto recien Ingresado',
      },
      editActivityIdInterna: {
        id: 8,
        nameEndpoint: 'Actualizar Id Interna a Proyecto Editado',
        urlEndPoint: '/mant-actividades/id-interna/edit/',
        params: '{jsonActivityIdInterna, idInterna}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Actualizar la Id Interna al proyecto a Editar',
      },
      deleteActivityIdInterna: {
        id: 9,
        nameEndpoint: 'Eliminar Id Interna a Proyecto',
        urlEndPoint: '/mant-actividades/id-interna/delete/',
        params: '{idInterna}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar la Id Interna al proyecto',
      },
      // NAM | 2019-02-28 | Mapping Ubicaciones de Actividades
      newActivityUbicacion: {
        id: 10,
        nameEndpoint: 'Agregar Ubicacion a Proyecto',
        urlEndPoint: '/mant-actividades/ubicaciones/new',
        params: '{ jsonUbicacionActivity }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Agregar la Ubicacion al proyecto recien Ingresado',
      },
      listAllActivityUbicaciones: {
        id: 11,
        nameEndpoint: 'Listar todas las Ubicaciones de los Proyecto',
        urlEndPoint: '/mant-actividades/ubicaciones',
        params: '{}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todas las Ubicaciones de los proyectos',
      },
      findByIdActivity: {
        id: 12,
        nameEndpoint: 'Listar todas las Ubicaciones de un Proyecto',
        urlEndPoint: '/mant-actividades/ubicaciones/findByIdActividadUbicacion/',
        params: '{ idActividadUbicacion }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todas las Ubicaciones del proyecto a consultado',
      },
      deleteActivityUbicacion: {
        id: 13,
        nameEndpoint: 'Eliminar Id Interna a Proyecto',
        urlEndPoint: '/mant-actividades/ubicaciones/delete/',
        params: '{ idUbicacionImpl}/{idActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar la Ubicacion al proyecto, selecionado',
      },
      findAllSectoresOcdeCad: { // Modulo de Sectores OCDE/CAD
        id: 14,
        nameEndpoint: 'findAllSectoresOcdeCad',
        urlEndPoint: '/sectores/ocde-cad',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos los Sectores OCDE/CAD registrados en la BD',
      },
      findByIdSectorOcdeCad: {
        id: 15,
        nameEndpoint: 'findByIdSectorOcdeCad',
        urlEndPoint: '/sectores/ocde-cad/findByIdSector/',
        params: '{ idSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Sector OCDE/CAD consultado',
      },
      findByIdNivelSectorOcdeCad: {
        id: 16,
        nameEndpoint: 'findByIdNivelSectorOcdeCad',
        urlEndPoint: '/sectores/ocde-cad/findByIdNivelSector/',
        params: '{ idNivelSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Sector OCDE/CAD consultado, por el Nivel que pertenencen',
      },
      findByIdNivelSectorAndSectorPadreOcdeCad: {
        id: 17,
        nameEndpoint: 'findByIdNivelSectorAndSectorPadreOcdeCad',
        urlEndPoint: '/sectores/ocde-cad/findByIdNivelSector/',
        params: '{ idNivelSector, sectorPadreId }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Sector OCDE/CAD consultado, por el Sector Padre y Nivel que pertenencen',
      },
      newActividadSectorOcdeCad: {
        id: 18,
        nameEndpoint: 'newActividadSectorOcdeCad',
        urlEndPoint: '/mant-actividades/sectores/ocde-cad-proyecto/new',
        params: '{ jsonSendActividadSectorOcdeCad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el Sector OCDE/CAD enviado y asociarlo al Proyecto',
      },
      deleteActividadSectorOcdeCad: {
        id: 19,
        nameEndpoint: 'deleteActividadSectorOcdeCad',
        urlEndPoint: '/mant-actividades/sectores/ocde-cad-proyecto/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el Sector OCDE/CAD enviado y asociarlo al Proyecto',
      },
      findAllSectoresGobierno: { // Modulo de Sectores de Gobierno
        id: 20,
        nameEndpoint: 'findAllSectoresGobierno',
        urlEndPoint: '/sectores/gobierno',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos los Sectores Gobierno registrados en la BD',
      },
      findByIdSectorGobierno: {
        id: 21,
        nameEndpoint: 'findByIdSectorGobierno',
        urlEndPoint: '/sectores/gobierno/findByIdSector/',
        params: '{ idSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Sector Gobierno consultado',
      },
      findByIdNivelSectorGobierno: {
        id: 22,
        nameEndpoint: 'findByIdNivelSectorGobierno',
        urlEndPoint: '/sectores/gobierno/findByIdNivelSector/',
        params: '{ idNivelSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Sector Gobierno consultado, por el Nivel que pertenencen',
      },
      findByIdNivelSectorAndSectorPadreGobierno: {
        id: 23,
        nameEndpoint: 'findByIdNivelSectorAndSectorPadreGobierno',
        urlEndPoint: '/sectores/gobierno/findByIdNivelSector/',
        params: '{ idNivelSector, sectorPadreId }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Sector Gobierno consultado, por el Sector Padre y Nivel que pertenencen',
      },
      newActividadSectorGobierno: {
        id: 24,
        nameEndpoint: 'newActividadSectorGobierno',
        urlEndPoint: '/mant-actividades/sectores/gobierno-proyecto/new',
        params: '{ jsonSendActividadSectorGobierno }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el Sector Gobierno enviado y asociarlo al Proyecto',
      },
      deleteActividadSectorGobierno: {
        id: 25,
        nameEndpoint: 'deleteActividadSectorGobierno',
        urlEndPoint: '/mant-actividades/sectores/gobierno-proyecto/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el Sector Gobierno enviado y asociarlo al Proyecto',
      },
      findAllSectoresCamposTransversales: { // Modulo de Campos Transversales
        id: 26,
        nameEndpoint: 'findAllSectoresCamposTransversales',
        urlEndPoint: '/sectores/campos-transversales',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos los Campos Transversales registrados en la BD',
      },
      findByIdSectorCamposTransversales: {
        id: 27,
        nameEndpoint: 'findByIdSectorGobierno',
        urlEndPoint: '/sectores/campos-transversales/findByIdSector/',
        params: '{ idSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Sector Gobierno consultado',
      },
      findByIdNivelSectorCamposTransversales: {
        id: 28,
        nameEndpoint: 'findByIdNivelSectorCamposTransversales',
        urlEndPoint: '/sectores/campos-transversales/findByIdNivelSector/',
        params: '{ idNivelSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Campo Transversal consultado, por el Nivel que pertenencen',
      },
      findByIdNivelSectorAndSectorPadreCamposTransversales: {
        id: 29,
        nameEndpoint: 'findByIdNivelSectorAndSectorPadreCamposTransversales',
        urlEndPoint: '/sectores/campos-transversales/findByIdNivelSector/',
        params: '{ idNivelSector, sectorPadreId }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Campo Transversal consultado, por el Sector Padre y Nivel que pertenencen',
      },
      newActividadSectorCamposTransversales: {
        id: 30,
        nameEndpoint: 'newActividadSectorCamposTransversales',
        urlEndPoint: '/mant-actividades/sectores/campos-transversales-proyecto/new',
        params: '{ jsonSendActividadSectorCampoTransversal }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el Campo Transversal enviado y asociarlo al Proyecto',
      },
      deleteActividadSectorCamposTransversales: {
        id: 31,
        nameEndpoint: 'deleteActividadSectorGobierno',
        urlEndPoint: '/mant-actividades/sectores/campos-transversales-proyecto/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el Campo Transversal enviado y asociarlo al Proyecto',
      },
      // Programas de Nacion
      findAllProgramasPlanNacion: { // Modulo de Plan de Nacion
        id: 32,
        nameEndpoint: 'findAllProgramasPlanNacion',
        urlEndPoint: '/programas/plan-nacion',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos los Planes de Nacion registrados en la BD',
      },
      findByIdProgramaPlanNacion: {
        id: 33,
        nameEndpoint: 'findByIdProgramaPlanNacion',
        urlEndPoint: '/programas/plan-nacion/findByIdPrograma/',
        params: '{ idPrograma }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Plan de Nacion consultado',
      },
      findByIdNivelProgramaPlanNacion: {
        id: 34,
        nameEndpoint: 'findByIdNivelProgramaPlanNacion',
        urlEndPoint: '/programas/plan-nacion/findByIdNivelPrograma/',
        params: '{ idNivelSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Plan de Nacion consultado, por el Nivel que pertenencen',
      },
      findByIdNivelProgramaPlanNacionPadre: {
        id: 35,
        nameEndpoint: 'findByIdNivelProgramaPlanNacionPadre',
        urlEndPoint: '/programas/plan-nacion/findByIdNivelPrograma/',
        params: '{ idNivelSector, sectorPadreId }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Plan de Nacion consultado, por el Programa Padre y Nivel que pertenencen',
      },
      newActividadProgramaPlanNacion: {
        id: 36,
        nameEndpoint: 'newActividadProgramaPlanNacion',
        urlEndPoint: '/mant-actividades/programas/plan-nacion-proyecto/new',
        params: '{ jsonSendActividadProgramaPlanNacion }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el Plan de Nacion enviado y asociarlo al Proyecto',
      },
      deleteActividadProgramaPlanNacion: {
        id: 37,
        nameEndpoint: 'deleteActividadProgramaPlanNacion',
        urlEndPoint: '/mant-actividades/programas/plan-nacion-proyecto/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el Plan de Nacion enviado y asociarlo al Proyecto',
      },
      findAllProgramasVidaMejor: { // Modulo de Vida Mejor
        id: 38,
        nameEndpoint: 'findAllProgramasVidaMejor',
        urlEndPoint: '/programas/vida-mejor',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos Vida Mejor registrados en la BD',
      },
      findByIdProgramaVidaMejor: {
        id: 39,
        nameEndpoint: 'findByIdProgramaVidaMejor',
        urlEndPoint: '/programas/vida-mejor/findByIdPrograma/',
        params: '{ idPrograma }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar Vida Mejor consultado',
      },
      findByIdNivelProgramaVidaMejor: {
        id: 40,
        nameEndpoint: 'findByIdNivelProgramaVidaMejor',
        urlEndPoint: '/programas/vida-mejor/findByIdNivelPrograma/',
        params: '{ idNivelSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar Vida Mejor consultado, por el Nivel que pertenencen',
      },
      findByIdNivelProgramaVidaMejorPadre: {
        id: 41,
        nameEndpoint: 'findByIdNivelProgramaVidaMejorPadre',
        urlEndPoint: '/programas/vida-mejor/findByIdNivelPrograma/',
        params: '{ idNivelSector, sectorPadreId }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar Vida Mejor consultado, por el Programa Padre y Nivel que pertenencen',
      },
      newActividadProgramaVidaMejor: {
        id: 42,
        nameEndpoint: 'newActividadProgramaVidaMejor',
        urlEndPoint: '/mant-actividades/programas/vida-mejor-proyecto/new',
        params: '{ jsonSendActividadProgramaPlanNacion }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar Vida Mejor enviado y asociarlo al Proyecto',
      },
      deleteActividadProgramaVidaMejor: {
        id: 43,
        nameEndpoint: 'deleteActividadProgramaVidaMejor',
        urlEndPoint: '/mant-actividades/programas/vida-mejor-proyecto/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar Vida Mejor enviado y asociarlo al Proyecto',
      },
      findAllSectoresOds: { // Modulo de ODS
        id: 44,
        nameEndpoint: 'findAllSectoresOds',
        urlEndPoint: '/sectores/ods',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos ODS registrados en la BD',
      },
      findByIdSectorOds: {
        id: 45,
        nameEndpoint: 'findByIdSectorOds',
        urlEndPoint: '/sectores/ods/findByIdSector/',
        params: '{ idPrograma }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar ODS consultado',
      },
      findByIdNivelSectorOds: {
        id: 46,
        nameEndpoint: 'findByIdNivelSectorOds',
        urlEndPoint: '/sectores/ods/findByIdNivelSector/',
        params: '{ idNivelSector }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar ODS consultado, por el Nivel que pertenencen',
      },
      findByIdNivelSectorOdsPadre: {
        id: 47,
        nameEndpoint: 'findByIdNivelSectorOdsPadre',
        urlEndPoint: '/sectores/ods/findByIdNivelSector/',
        params: '{ idNivelSector, sectorPadreId }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar ODS consultado, por el Programa Padre y Nivel que pertenencen',
      },
      newActividadSectorOds: {
        id: 48,
        nameEndpoint: 'newActividadSectorOds',
        urlEndPoint: '/mant-actividades/sectores/ods-proyecto/new',
        params: '{ jsonSendActividadProgramaPlanNacion }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar ODS enviado y asociarlo al Proyecto',
      },
      deleteActividadSectorOds: {
        id: 49,
        nameEndpoint: 'deleteActividadSectorOds',
        urlEndPoint: '/mant-actividades/sectores/ods-proyecto/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar ODS enviado y asociarlo al Proyecto',
      },
      // Programas Vision de Pais
      findAllProgramaVisionPais: {
        id: 50,
        nameEndpoint: 'findAllProgramaVisionPais',
        urlEndPoint: '/programas/vision-pais',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos datos de Vision de Pais registrados en la BD',
      },
      findByIdProgramaVisionPais: {
        id: 51,
        nameEndpoint: 'findByIdProgramaVisionPais',
        urlEndPoint: '/programas/vision-pais/findByIdPrograma',
        params: '{ idPrograma }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Vision  Pais consultado',
      },
      findByIdNivelProgramaVisionPais: {
        id: 52,
        nameEndpoint: 'findByIdNivelProgramaVisionPais',
        urlEndPoint: '/programas/vision-pais/findByIdNivelPrograma',
        params: '{ idNivelPrograma }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar los datos de Vision  Pais consultado, por el nivel que pertenencen',
      },
      findByIdNivelProgramaVisionPaisPadre: {
        id: 53,
        nameEndpoint: 'findByIdNivelProgramaVisionPaisPadre',
        urlEndPoint: '/programas/vision-pais/findByIdNivelPrograma/findByProgramaPadreId',
        params: '{ idNivelPrograma,sectorPadreId }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar los datos de Vision Pais consultado, por el Programa Padre y Nivel que pertenencen',
      },
      newActividadProgramaVisionPais: {
        id: 54,
        nameEndpoint: 'newActividadProgramaVisionPais',
        urlEndPoint: '/mant-actividades/programas/vision-pais-proyecto/new',
        params: '{ jsonSendActividadProgramaVisionPais }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato Vision Pais enviado y asociarlo al Proyecto',
      },
      deleteActividadProgramaVisionPais: {
        id: 55,
        nameEndpoint: 'deleteActividadProgramaVisionPais',
        urlEndPoint: '/mant-actividades/programas/vision-pais-proyecto/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Vision Pais enviado y asociarlo al Proyecto',
      },
      // Programas Politicas Publicas y Estrategias Nacionales
      findAllProgramasPoliticasPublicas: {
        id: 56,
        nameEndpoint: 'findAllProgramasPoliticasPublicas',
        urlEndPoint: '/programas/politica-publica',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos datos de Politicas Publicas registrados en la BD',
      },
      findByIdProgramaPoliticasPublicas: {
        id: 57,
        nameEndpoint: 'findByIdProgramaPoliticasPublicas',
        urlEndPoint: '/programas/politica-publica/findByIdPrograma',
        params: '{ idPrograma }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Politicas Publicas consultado',
      },
      findByIdNivelProgramaPoliticasPublicas: {
        id: 58,
        nameEndpoint: 'findByIdNivelProgramaPoliticasPublicas',
        urlEndPoint: '/programas/politica-publica/findByIdNivelPrograma',
        params: '{ idNivelPrograma }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar los datos de Politicas Publicas consultado, por el nivel que pertenencen',
      },
      findByIdNivelProgramaPoliticasPublicasPadre: {
        id: 59,
        nameEndpoint: 'findByIdNivelProgramaPoliticasPublicasPadre',
        urlEndPoint: '/programas/politica-publica/findByIdNivelPrograma/findByProgramaPadreId',
        params: '{ idNivelPrograma,sectorPadreId }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar los datos de Politicas Publicas consultado, por el Programa Padre y Nivel que pertenencen',
      },
      newActividadProgramaPoliticasPublicas: {
        id: 60,
        nameEndpoint: 'newActividadProgramaPoliticasPublicas',
        urlEndPoint: '/mant-actividades/programas/politica-publica-proyecto/new',
        params: '{ jsonSendActividadProgramaPoliticasPublicas }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato Politicas Publicas enviado y asociarlo al Proyecto',
      },
      deleteActividadProgramaPoliticasPublicas: {
        id: 61,
        nameEndpoint: 'deleteActividadProgramaPoliticasPublicas',
        urlEndPoint: '/mant-actividades/programas/politica-publica-proyecto/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Politicas Publicas enviado y asociarlo al Proyecto',
      },
      // Organizaciones de Proyectos | Socio al Desarrollo
      findAllSocioDesarrollo: {
        id: 62,
        nameEndpoint: 'findAllSocioDesarrollo',
        urlEndPoint: '/mant-actividades/organizaciones/socio-desarrollo',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos datos de Socios al Desarrollo registrados en la BD',
      },
      findByIdActividad: {
        id: 63,
        nameEndpoint: 'findByIdActividad',
        urlEndPoint: '/mant-actividades/organizaciones/socio-desarrollo/findByIdActividad/',
        params: '{ idActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Socios al Desarrollo consultado',
      },
      findByCodigoActividad: {
        id: 64,
        nameEndpoint: 'findByCodigoActividad',
        urlEndPoint: '/mant-actividades/organizaciones/socio-desarrollo/findByCodigoActividad/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Socios al Desarrollo consultado',
      },
      newActividadSocioDesarrollo: {
        id: 65,
        nameEndpoint: 'newActividadSocioDesarrollo',
        urlEndPoint: '/mant-actividades/organizaciones/socio-desarrollo/new',
        params: '{ jsonSendActividadSocioDesarrollo }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato Socio Desarrollo enviado y asociarlo al Proyecto',
      },
      deleteActividadSocioDesarrollo: {
        id: 66,
        nameEndpoint: 'deleteActividadSocioDesarrollo',
        urlEndPoint: '/mant-actividades/organizaciones/socio-desarrollo/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Socio Desarrollo enviado y asociarlo al Proyecto',
      }, // Modulo de Financiamiento de Proyectos | Encabezado
      newActividadFinanciamientoEnc: {
        id: 67,
        nameEndpoint: 'newActividadFinanciamientoEnc',
        urlEndPoint: '/mant-actividades/financiamiento/encabezado/new',
        params: '{ jsonSendActividadFinanciamientoEnc }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato de Encabezado de Financiamiento enviado y asociarlo al Proyecto',
      },
      deleteActividadFinanciamientoEnc: {
        id: 68,
        nameEndpoint: 'deleteActividadFinanciamientoEnc',
        urlEndPoint: '/mant-actividades/financiamiento/encabezado/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Encabezado de Financiamiento enviado y asociarlo al Proyecto',
      },
      editActividadFinanciamientoEnc: {
        id: 68.100,
        nameEndpoint: 'editActividadFinanciamientoEnc',
        urlEndPoint: '/mant-actividades/financiamiento/encabezado/edit/',
        params: '{ idActividadFinacEnc }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Encabezado de financiamiento del Proyecto',
      },
      findByIdActividadFinancEnc: {
        id: 68.101,
        nameEndpoint: 'findByIdActividadFinancEnc',
        urlEndPoint: '/mant-actividades/financiamiento/encabezado/findByIdActividad/',
        params: '{ idActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Encabezado de financiamiento del Proyecto',
      }, // Modulo de Financiamiento de Proyectos | Detalle
      newActividadFinanciamientoDet: {
        id: 69,
        nameEndpoint: 'newActividadFinanciamientoDet',
        urlEndPoint: '/mant-actividades/financiamiento/detalle/new',
        params: '{ jsonSendActividadFinanciamientoEnc }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato de Detalle de Financiamiento enviado y asociarlo al Proyecto',
      },
      deleteActividadFinanciamientoDet: {
        id: 70,
        nameEndpoint: 'deleteActividadFinanciamientoDet',
        urlEndPoint: '/mant-actividades/financiamiento/detalle/delete/',
        params: '{ codigoFinancDet }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Detalle de Financiamiento enviado y asociarlo al Proyecto',
      },
      findByIdActividadFinancEncDet: {
        id: 70.100,
        nameEndpoint: 'findByIdActividadFinancEncDetalle',
        urlEndPoint: '/mant-actividades/financiamiento/detalle/findByIdActividadFinancEnc/',
        params: '{ idActividadFinancEnc }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Detalle de financiamiento del Proyecto',
      },
      findByByCodigoFinancDet: {
        id: 70.101,
        nameEndpoint: 'findByIdActividadFinancEncDetalle',
        urlEndPoint: '/mant-actividades/financiamiento/detalle/findByCodigoFinancDet/',
        params: '{ codigoFinancDet }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Detalle de financiamiento del Proyecto',
      },
      editActividadFinanciamientoDet: {
        id: 70.102,
        nameEndpoint: 'editActividadFinanciamientoDet',
        urlEndPoint: '/mant-actividades/financiamiento/detalle/edit/',
        params: '{ idActividadFinancDet }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Actualiza el Detalle de financiamiento del Proyecto',
      },
      findByIdActividadFinancEncDetAndIdSocioDesarrollo: {
        id: 70.103,
        nameEndpoint: 'findByIdActividadFinancEncDetalle',
        urlEndPoint: '/mant-actividades/financiamiento/detalle/findByIdActividadFinancEncAndIdSocioDesarollo/',
        params: '{ idActividadFinancEnc, idSocioDesarrollo }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el Detalle de financiamiento del Proyecto, con el Socio al Desarrollo',
      }, // Modulo de Financiamiento de Proyectos | Compromisos
      newActividadFinanciamientoDetCompromiso: {
        id: 70.200,
        nameEndpoint: 'newActividadFinanciamientoDetCompromiso',
        urlEndPoint: '/mant-actividades/financiamiento/detalle-compromiso/new',
        params: '{ jsonSendActividadFinanciamientoDetCompromiso }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato de Detalle de Financiamiento Compromiso enviado y asociarlo al Proyecto',
      },
      deleteActividadFinanciamientoDetCompromiso: {
        id: 70.201,
        nameEndpoint: 'deleteActividadFinanciamientoDetCompromiso',
        urlEndPoint: '/mant-actividades/financiamiento/detalle-compromiso/delete/',
        params: '{ codigoFinancCompromiso }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Detalle de Financiamiento Compromiso enviado y asociarlo al Proyecto',
      },
      findByIdActividadDetComprisos: {
        id: 70.202,
        nameEndpoint: 'findByIdActividadDetComprisos',
        urlEndPoint: '/mant-actividades/financiamiento/detalle-compromiso/findByIdActividadDet/',
        params: '{ idActividadDet }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos los Compromisos del Proyecto',
      },
      editActividadFinanciamientoDetCompromiso: {
        id: 70.203,
        nameEndpoint: 'editActividadFinanciamientoDetCompromiso',
        urlEndPoint: '/mant-actividades/financiamiento/detalle-compromiso/edit/',
        params: '{ idActividadFinancDetCompromiso }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Actualizar Información de Compromisos del Proyecto',
      },
      // Organizaciones de Proyectos | Unidad Ejecutora
      findAllUnidadEjecutora: {
        id: 71,
        nameEndpoint: 'findAllUnidadEjecutora',
        urlEndPoint: '/mant-actividades/organizaciones/unidad-ejecutora',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos datos de Unidad Ejecutora registrados en la BD',
      },
      findByIdActividadUnidadEjecutora: {
        id: 72,
        nameEndpoint: 'findByIdActividadIdUnidadEjecutora',
        urlEndPoint: '/mant-actividades/organizaciones/unidad-ejecutora/findByIdActividad',
        params: '{ idActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Unidad Ejecutora consultado',
      },
      findByCodigoActividadUnidadEjecutora: {
        id: 73,
        nameEndpoint: 'findByCodigoActividadUnidadEjecutora',
        urlEndPoint: '/mant-actividades/organizaciones/unidad-ejecutora/findByCodigoActividad',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Unidad Ejecutora consultado',
      },
      newActividadUnidadEjecutora: {
        id: 74,
        nameEndpoint: 'newActividadUnidadEjecutora',
        urlEndPoint: '/mant-actividades/organizaciones/unidad-ejecutora/new',
        params: '{ jsonSendActividadUnidadEjecutora }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato Unidad Ejecutora enviado y asociarlo al Proyecto',
      },
      deleteActividadUnidadEjecutora: {
        id: 75,
        nameEndpoint: 'deleteActividadUnidadEjecutora',
        urlEndPoint: '/mant-actividades/organizaciones/unidad-ejecutora/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Unidad Ejecutora enviado y asociarlo al Proyecto',
      },
      editActividadUnidadEjecutora: {
        id: 75.1,
        nameEndpoint: 'editActividadUnidadEjecutora',
        urlEndPoint: '/mant-actividades/organizaciones/unidad-ejecutora/edit/',
        params: '{ idActividadUnidadEjecutora }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Edita el dato de Unidad Ejecutora enviado y asociarlo al Proyecto',
      },
      // Organizaciones de Proyectos | Admon Financiero
      findAllAdmonFinanciero: {
        id: 76,
        nameEndpoint: 'findAllAdmonFinanciero',
        urlEndPoint: '/mant-actividades/organizaciones/admon-financiero',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos datos de Admon Financiero registrados en la BD',
      },
      findByIdActividadAmonFinanciero: {
        id: 77,
        nameEndpoint: 'findByIdActividadAdmonFinanciero',
        urlEndPoint: '/mant-actividades/organizaciones/admon-financiero/findByIdActividadAdmonFinanciero',
        params: '{ idActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Admon Financiero consultado',
      },
      findByCodigoActividadAdmonFinanciero: {
        id: 78,
        nameEndpoint: 'findByCodigoActividadAdmonFinanciero',
        urlEndPoint: '/mant-actividades/organizaciones/admon-financiero/findByCodigoActividadAdmonFinanciero',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Admon Financiero consultado',
      },
      newActividadAmonFinanciero: {
        id: 79,
        nameEndpoint: 'newActividadAdmonFinanciero',
        urlEndPoint: '/mant-actividades/organizaciones/admon-financiero/new',
        params: '{ jsonSendActividadAdmonFinanciero }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato Admon Financiero enviado y asociarlo al Proyecto',
      },
      deleteActividadAdmonFinanciero: {
        id: 80,
        nameEndpoint: 'deleteActividadAdmonFinanciero',
        urlEndPoint: '/mant-actividades/organizaciones/admon-financiero/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Admon Financiero enviado y asociarlo al Proyecto',
      },
      // Organizaciones de Proyectos | Agencia Beneficiaria
      findAllAgenciaBeneficiaria: {
        id: 81,
        nameEndpoint: 'findAllAgenciaBeneficiaria',
        urlEndPoint: '/mant-actividades/organizaciones/agencia-beneficiaria',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos datos de Agencia Beneficiria registrados en la BD',
      },
      findByIdActividadAgenciaBeneficiaria: {
        id: 82,
        nameEndpoint: 'findByIdActividadAgenciaBeneficiaria',
        urlEndPoint: '/mant-actividades/organizaciones/agencia-beneficiaria/findByIdActividadAgenciaBeneficiaria',
        params: '{ idActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Agencia Beneficiaria consultado',
      },
      findByCodigoActividadAgenciaBeneficiaria: {
        id: 83,
        nameEndpoint: 'findByCodigoActividadAgenciaBeneficiaria',
        urlEndPoint: '/mant-actividades/organizaciones/agencia-beneficiaria/findByCodigoActividadAgenciaBeneficiaria',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar el dato de Agencia Beneficiaria consultado',
      },
      newActividadAgenciaBeneficiaria: {
        id: 84,
        nameEndpoint: 'newActividadAgenciaBeneficiaria',
        urlEndPoint: '/mant-actividades/organizaciones/agencia-beneficiaria/new',
        params: '{ jsonSendActividadAgenciaBeneficiaria }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Ingresar el dato Agencia Beneficiaria enviado y asociarlo al Proyecto',
      },
      editActividadAgenciaBeneficiaria: {
        id: 85,
        nameEndpoint: 'newActividadAgenciaBeneficiaria',
        urlEndPoint: '/mant-actividades/organizaciones/agencia-beneficiaria/edit',
        params: '{idActividadAgenciaEjecutora}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Actulizar el dato Agencia Beneficiaria enviado y asociarlo al Proyecto',
      },
      deleteActividadAgenciaBeneficiaria: {
        id: 86,
        nameEndpoint: 'deleteActividadAgenciaBeneficiaria',
        urlEndPoint: '/mant-actividades/organizaciones/agencia-beneficiaria/delete/',
        params: '{ codigoActividad }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Eliminar el dato de Agencia Beneficiaria enviado y asociarlo al Proyecto',
      },
      // Recursos de Proyecto (Documentos y links)
      findAllrecursosproyecto: {
        id: 87,
        nameEndpoint: 'findAllrecursosproyecto',
        urlEndPoint: '/mant-actividades/recursos-proyecto',
        params: '{ }',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Listar todos los Recursos de una Actividad de la BD',
      },
      downloadfilerecursosproyecto: {
        id: 88,
        nameEndpoint: 'downloadfilerecursosproyecto',
        urlEndPoint: '/mant-actividades/recursos-proyecto/downloadfile',
        params: '{filename}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Descarga el documento solicitado',
      },
      findByCodActividadRecurso: {
        id: 89,
        nameEndpoint: 'findByCodActividadRecurso',
        urlEndPoint: '/mant-actividades/recursos-proyecto/findByCodActividadRecurso',
        params: '{codActividadRecurso}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Descarga el documento solicitado',
      },
      finAllTipoRecursos: {
        id: 90,
        nameEndpoint: 'finAllTipoRecursos',
        urlEndPoint: '/mant-actividades/recursos-proyecto/tipos',
        params: '{}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Retorna el listado de todos los tipos de recursos de la bd',
      },
      findByIdTipoRecursos: {
        id: 91,
        nameEndpoint: 'findByIdTipoRecursos',
        urlEndPoint: '/mant-actividades/recursos-proyecto/tipos',
        params: '{idTipoRecursos}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Retorna el listado de todos los tipos de recursos por id de la bd',
      },
      uploadfilerecursosproyecto: {
        id: 92,
        nameEndpoint: 'uploadfilerecursosproyecto',
        urlEndPoint: '/mant-actividades/recursos-proyecto/uploadFile',
        params: '{uploadFile}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Retorna el listado de todos los tipos de recursos por id de la bd',
      },
      uploadMuLtiplefilerecursosproyecto: {
        id: 93,
        nameEndpoint: 'uploadMuLtiplefilerecursosproyecto',
        urlEndPoint: '/mant-actividades/recursos-proyecto/uploadMultipleFiles',
        params: '{uploadMultipleFile}',
        groupEndPoint: 'actividadesCRUDGroup',
        descEndPoint: 'Retorna el listado de todos los tipos de recursos por id de la bd',
      },
    }, // modulo de mantenimientos generico de usuarios
    endPointMantGenericosUsuario: {
      listAllUsuarios: {
        id: 1,
        nameEndpoint: 'List All Usuarios',
        urlEndPoint: '/usuarios',
        groupEndPoint: 'mantGenericosUsuarioGroup',
        descEndPoint: 'Listar todos los Usuarios',
      },
      newUsuario: {
        id: 2,
        nameEndpoint: 'nuevo usuario',
        urlEndPoint: '/usuarios/new',
        groupEndPoint: 'mantGenericosUsuarioGroup',
        descEndPoint: 'crear nuevo Usuarios',
      },
      getAllTipoUsuario: {
        id: 3,
        nameEndpoint: 'listar tipo usuario',
        urlEndPoint: '/tipos/findByIdGrupo/',
        groupEndPoint: 'mantGenericosUsuarioGroup',
        descEndPoint: 'listar los tipo de usuarios',
      },
      usuarioUpdate: {
        id: 4,
        nameEndpoint: 'Actualizar los usuarios',
        urlEndPoint: '/usuarios/update/',
        groupEndPoint: 'mantGenericosUsuarioGroup',
        descEndPoint: 'Actualizar los usuarios',
      },
      usuarioValidate: {
        id: 5,
        nameEndpoint: 'Codigos usuarios',
        urlEndPoint: '/usuarios/findByCod/',
        groupEndPoint: 'mantGenericosUsuarioGroup',
        descEndPoint: 'comparar codigos de los usuarios',
      },
      deleteUsuario: {
        id: 6,
        nameEndpoint: 'inhabilitar los usuarios',
        urlEndPoint: '/usuarios/delete/',
        groupEndPoint: 'mantGenericosUsuarioGroup',
        descEndPoint: 'inhabilita los usuarios',
      },
    },
    endPointImplementacion: { // NAM | Implenetacion de Proyectos
      listAllNivelImplementacion: {
        id: 1,
        nameEndpoint: 'List All Nivel de Implementacion',
        urlEndPoint: '/ubicacion-geografica/nivel-implementacion',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar todos los Niveles de Implementacion',
      },
      findByIdNivel: {
        id: 2,
        nameEndpoint: 'List Nivel de Implementacion',
        urlEndPoint: '/ubicacion-geografica/nivel-implementacion/findByIdNivel/',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar el Nivel de Implementacion, buscado por el ID',
      },
      listAllNivelUbicacionImplementacion: {
        id: 3,
        nameEndpoint: 'List All Nivel de Ubicacion de Implementacion',
        urlEndPoint: '/ubicacion-geografica/nivel-ubicacion-implementacion',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar Todos Nivel de Ubicacion de Implementacion',
      },
      findByIdNivelUbicacion: {
        id: 4,
        nameEndpoint: 'List Nivel de Ubicacion de Implementacion',
        urlEndPoint: '/ubicacion-geografica/nivel-ubicacion-implementacion/findByIdNivelUbicacion/',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar el Nivel de Ubicacion de Implementacion, buscado por el ID',
      },
      findByIdNivelImplementacion: {
        id: 5,
        nameEndpoint: 'List Nivel de Ubicacion de Implementacion, por Nivel de Implementacion',
        urlEndPoint: '/ubicacion-geografica/nivel-ubicacion-implementacion/findByIdNivelImplementacion/',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar el Nivel de Ubicacion de Implementacion, buscado por el ID Nivel de Implementacion',
      },
      listAllUbicaciones: {
        id: 6,
        nameEndpoint: 'List de Ubicaciones',
        urlEndPoint: '/ubicacion-geografica/ubicacion-implementacion',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar el Nivel de Ubicacion de Implementacion, buscado por el ID Nivel de Implementacion',
      },
      findByIdUbicacion: {
        id: 7,
        nameEndpoint: 'List de Ubicacion, por Id',
        urlEndPoint: '/ubicacion-geografica/ubicacion-implementacion/findByIdUbicacion/',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar la Ubicacion de Implementacion, buscado por el ID',
      },
      findByUbicIdNivelImplementacion: {
        id: 8,
        nameEndpoint: 'List de Ubicaciones, por Nivel de Implementacion',
        urlEndPoint: '/ubicacion-geografica/ubicacion-implementacion/findByIdNivelImplementacion/',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar las Ubicaciones de Implementacion, buscado por el ID Nivel de Implementacion',
      },
      findByUbicIdNivelUbicacion: {
        id: 9,
        nameEndpoint: 'List de Ubicaciones, por Nivel de Ubicacion',
        urlEndPoint: '/ubicacion-geografica/ubicacion-implementacion/findByIdNivelUbicacion/',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar las Ubicaciones de Implementacion, buscado por el ID de Nivel Ubicacion',
      },
      findByUbicIdNivelImplAndIdNivelUbicacion: {
        id: 10,
        nameEndpoint: 'List de Ubicaciones, por Nivel de Implementacion y Nivel de Ubicacion de Implementacion',
        urlEndPoint: '/ubicacion-geografica/ubicacion-implementacion/findByIdNivelImplementacionAndIdNivelUbicacion/',
        groupEndPoint: 'endPointImplementacion',
        descEndPoint: 'Listar las Ubicaciones de Implementacion, buscado por el ID Nivel de Implementacion y Nivel de Unicacion de Implementacion',
      },
    },
  }
} // FIN de Clase
